language: ruby
cache:
  - bundler
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
test:
  adapter: postgresql
  database: travis_ci_test
# before_script:
#   - cp config/database.yml.travis config/database.yml
before_install:
  - gem install rake
