# script:
#   - "bundle exec rake neo4j:install['community-2.2.0-M02'] neo4j:start default --trace"
language: ruby
rvm:
  -  2.6.5
script: true


deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  skip_cleanup: true
  on:
    branch: main
