language: ruby
dist: focal
script: echo "its bulit!"
#travis bulid, don't forget to line!
services:
  - postgresql
  before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  test:
  adapter: postgresql
  database: travis_ci_test
