language: ruby
rvm:
- 2.6.5
install: skip
script:
  - cat test.txt
before_install:
- openssl aes-256-cbc -K $encrypted_4b6fcb2d521e_key -iv $encrypted_4b6fcb2d521e_iv
  -in test.txt.enc -out test.txt -d
deploy:
  provider: releases
  api_key: "$GITHUB_OAUTH_TOKEN"
  skip_cleanup: true
  file: README.md
  branches:
    only:
    - main
    - "/v\\d+\\.\\d+[a-z]/"
  on:
    tags: true
